//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.29 at 04:01:51 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://github.com/nikson/demo-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.nikson.demo_ws;
